export enum UserRole {
  GROUPON_REGISTRAR = 'GROUPON_REGISTRAR',
  AUDIT_SUPERVISOR = 'AUDIT_SUPERVISOR',
  REVIEW_LEADER = 'REVIEW_LEADER',
  LEADER_OPERATOR = 'LEADER_OPERATOR',
  FULFILLMENT_SPECIALIST = 'FULFILLMENT_SPECIALIST',
  CITY_MANAGER = 'CITY_MANAGER',
}
