// DO NOT EDIT. This file is auto-generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$0 from "./islands/LoginIsland.tsx";
import * as $$1 from "./islands/OrderListIsland.tsx";
import * as $$2 from "./islands/OrderDetailIsland.tsx";
import * as $$3 from "./islands/BatchProcessIsland.tsx";
import * as $$4 from "./islands/CreateOrderIsland.tsx";
import * as $$5 from "./routes/login.tsx";
import * as $$6 from "./routes/index.tsx";
import * as $$7 from "./routes/create.tsx";
import * as $$8 from "./routes/batch.tsx";
import * as $$9 from "./routes/orders/[id].tsx";
import * as $$10 from "./routes/_layout.tsx";

const manifest = {
  routes: {
    "./routes/login.tsx": $$5,
    "./routes/index.tsx": $$6,
    "./routes/create.tsx": $$7,
    "./routes/batch.tsx": $$8,
    "./routes/orders/[id].tsx": $$9,
    "./routes/_layout.tsx": $$10,
  },
  islands: {
    "./islands/LoginIsland.tsx": $$0,
    "./islands/OrderListIsland.tsx": $$1,
    "./islands/OrderDetailIsland.tsx": $$2,
    "./islands/BatchProcessIsland.tsx": $$3,
    "./islands/CreateOrderIsland.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
