// DO NOT EDIT. This file is auto-generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$0 from "./routes/_app.tsx";
import * as $$1 from "./routes/index.tsx";
import * as $$2 from "./routes/flows/index.tsx";
import * as $$3 from "./routes/flows/[id].tsx";
import * as $$4 from "./islands/FlowListIsland.tsx";
import * as $$5 from "./islands/FlowDetailIsland.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $$0,
    "./routes/index.tsx": $$1,
    "./routes/flows/index.tsx": $$2,
    "./routes/flows/[id].tsx": $$3,
  },
  islands: {
    "./islands/FlowListIsland.tsx": $$4,
    "./islands/FlowDetailIsland.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
