/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SwitchRoleImport } from './routes/switch-role'
import { Route as ProjectsNewImport } from './routes/projects.new'
import { Route as ProjectsImport } from './routes/projects'
import { Route as LoginImport } from './routes/login'
import { Route as DeadlineImport } from './routes/deadline'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIdImport } from './routes/projects.$id'

// Create/Update Routes

const SwitchRoleRoute = SwitchRoleImport.update({
  path: '/switch-role',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsNewRoute = ProjectsNewImport.update({
  path: '/projects/new',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRoute = ProjectsImport.update({
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DeadlineRoute = DeadlineImport.update({
  path: '/deadline',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIdRoute = ProjectsIdImport.update({
  path: '/projects/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/deadline': {
      id: '/deadline'
      path: '/deadline'
      fullPath: '/deadline'
      preLoaderRoute: typeof DeadlineImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsImport
      parentRoute: typeof rootRoute
    }
    '/switch-role': {
      id: '/switch-role'
      path: '/switch-role'
      fullPath: '/switch-role'
      preLoaderRoute: typeof SwitchRoleImport
      parentRoute: typeof rootRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdImport
      parentRoute: typeof rootRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deadline': typeof DeadlineRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/switch-role': typeof SwitchRoleRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deadline': typeof DeadlineRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/switch-role': typeof SwitchRoleRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/deadline': typeof DeadlineRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/switch-role': typeof SwitchRoleRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deadline'
    | '/login'
    | '/projects'
    | '/switch-role'
    | '/projects/$id'
    | '/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deadline'
    | '/login'
    | '/projects'
    | '/switch-role'
    | '/projects/$id'
    | '/projects/new'
  id:
    | '__root__'
    | '/'
    | '/deadline'
    | '/login'
    | '/projects'
    | '/switch-role'
    | '/projects/$id'
    | '/projects/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeadlineRoute: typeof DeadlineRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  SwitchRoleRoute: typeof SwitchRoleRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  DeadlineRoute,
  LoginRoute,
  ProjectsRoute,
  SwitchRoleRoute,
  ProjectsIdRoute,
  ProjectsNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/deadline",
        "/login",
        "/projects",
        "/switch-role",
        "/projects/$id",
        "/projects/new"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/deadline": {
      "filePath": "deadline.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/projects": {
      "filePath": "projects.tsx"
    },
    "/switch-role": {
      "filePath": "switch-role.tsx"
    },
    "/projects/$id": {
      "filePath": "projects.$id.tsx"
    },
    "/projects/new": {
      "filePath": "projects.new.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
