# Generated by Django 4.2.7 on 2026-06-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForeignTradeOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="订单编号"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="客户名称"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="产品名称"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="数量"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="金额(USD)",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="目的国"
                    ),
                ),
                (
                    "inquiry_content",
                    models.TextField(
                        blank=True, default="", verbose_name="客户询盘内容"
                    ),
                ),
                (
                    "quote_content",
                    models.TextField(
                        blank=True, default="", verbose_name="报价确认信息"
                    ),
                ),
                (
                    "order_content",
                    models.TextField(
                        blank=True, default="", verbose_name="订单签订信息"
                    ),
                ),
                (
                    "quote_confirmed",
                    models.BooleanField(default=False, verbose_name="报价已确认"),
                ),
                (
                    "order_signed",
                    models.BooleanField(default=False, verbose_name="订单已签订"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_dispatch", "待派发"),
                            ("processing", "处理中"),
                            ("closed", "已关闭"),
                        ],
                        default="pending_dispatch",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("inquiry", "客户询盘"),
                            ("quote_confirmation", "报价确认"),
                            ("order_signing", "订单签订"),
                            ("archived", "已归档"),
                        ],
                        default="inquiry",
                        max_length=30,
                        verbose_name="当前阶段",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="责任人"
                    ),
                ),
                (
                    "current_handler",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="当前处理人",
                    ),
                ),
                (
                    "current_handler_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clerk", "外贸登记员"),
                            ("supervisor", "外贸审核主管"),
                            ("reviewer", "外贸公司复核负责人"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="当前处理人角色",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "due_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止时间"
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "is_exception",
                    models.BooleanField(default=False, verbose_name="是否异常"),
                ),
                (
                    "exception_tags",
                    models.JSONField(blank=True, default=list, verbose_name="异常标签"),
                ),
                (
                    "result",
                    models.TextField(blank=True, default="", verbose_name="办理结果"),
                ),
                (
                    "return_reason",
                    models.TextField(blank=True, default="", verbose_name="退回原因"),
                ),
            ],
            options={
                "verbose_name": "外贸订单",
                "verbose_name_plural": "外贸订单",
                "db_table": "foreign_trade_order",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("submit", "提交"),
                            ("dispatch", "派发"),
                            ("process", "办理"),
                            ("review", "复核"),
                            ("return", "退回补正"),
                            ("correct", "补正"),
                            ("close", "关闭归档"),
                            ("batch_process", "批量处理"),
                        ],
                        max_length=30,
                        verbose_name="操作动作",
                    ),
                ),
                ("operator", models.CharField(max_length=100, verbose_name="操作人")),
                (
                    "operator_role",
                    models.CharField(
                        choices=[
                            ("clerk", "外贸登记员"),
                            ("supervisor", "外贸审核主管"),
                            ("reviewer", "外贸公司复核负责人"),
                        ],
                        max_length=30,
                        verbose_name="操作人角色",
                    ),
                ),
                (
                    "operate_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending_dispatch", "待派发"),
                            ("processing", "处理中"),
                            ("closed", "已关闭"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="原状态",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending_dispatch", "待派发"),
                            ("processing", "处理中"),
                            ("closed", "已关闭"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="新状态",
                    ),
                ),
                (
                    "from_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inquiry", "客户询盘"),
                            ("quote_confirmation", "报价确认"),
                            ("order_signing", "订单签订"),
                            ("archived", "已归档"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="原阶段",
                    ),
                ),
                (
                    "to_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inquiry", "客户询盘"),
                            ("quote_confirmation", "报价确认"),
                            ("order_signing", "订单签订"),
                            ("archived", "已归档"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="新阶段",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="操作说明"),
                ),
                (
                    "evidence_required",
                    models.BooleanField(default=False, verbose_name="是否需证据"),
                ),
                (
                    "evidence_provided",
                    models.BooleanField(default=False, verbose_name="是否已提供证据"),
                ),
                (
                    "version_before",
                    models.IntegerField(default=0, verbose_name="操作前版本"),
                ),
                (
                    "version_after",
                    models.IntegerField(default=0, verbose_name="操作后版本"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_records",
                        to="orders.foreigntradeorder",
                        verbose_name="外贸订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "处理记录",
                "verbose_name_plural": "处理记录",
                "db_table": "processing_record",
                "ordering": ["-operate_time"],
            },
        ),
        migrations.CreateModel(
            name="OrderAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="文件路径"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="文件类型"
                    ),
                ),
                ("file_size", models.IntegerField(default=0, verbose_name="文件大小")),
                (
                    "uploaded_by",
                    models.CharField(max_length=100, verbose_name="上传人"),
                ),
                (
                    "uploaded_by_role",
                    models.CharField(
                        choices=[
                            ("clerk", "外贸登记员"),
                            ("supervisor", "外贸审核主管"),
                            ("reviewer", "外贸公司复核负责人"),
                        ],
                        max_length=30,
                        verbose_name="上传人角色",
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="说明"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inquiry", "客户询盘"),
                            ("quote_confirmation", "报价确认"),
                            ("order_signing", "订单签订"),
                            ("archived", "已归档"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="所属阶段",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="orders.foreigntradeorder",
                        verbose_name="外贸订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单附件",
                "verbose_name_plural": "订单附件",
                "db_table": "order_attachment",
                "ordering": ["-upload_time"],
            },
        ),
        migrations.CreateModel(
            name="ExceptionReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_type",
                    models.CharField(max_length=50, verbose_name="异常类型"),
                ),
                ("reason_detail", models.TextField(verbose_name="异常详情")),
                (
                    "corrective_action",
                    models.TextField(blank=True, default="", verbose_name="补正动作"),
                ),
                (
                    "recorded_by",
                    models.CharField(max_length=100, verbose_name="记录人"),
                ),
                (
                    "recorded_by_role",
                    models.CharField(
                        choices=[
                            ("clerk", "外贸登记员"),
                            ("supervisor", "外贸审核主管"),
                            ("reviewer", "外贸公司复核负责人"),
                        ],
                        max_length=30,
                        verbose_name="记录人角色",
                    ),
                ),
                (
                    "record_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="是否已解决"),
                ),
                (
                    "resolve_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exception_reasons",
                        to="orders.foreigntradeorder",
                        verbose_name="外贸订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "异常原因",
                "verbose_name_plural": "异常原因",
                "db_table": "exception_reason",
                "ordering": ["-record_time"],
            },
        ),
        migrations.CreateModel(
            name="AuditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(verbose_name="审计备注")),
                ("noted_by", models.CharField(max_length=100, verbose_name="备注人")),
                (
                    "noted_by_role",
                    models.CharField(
                        choices=[
                            ("clerk", "外贸登记员"),
                            ("supervisor", "外贸审核主管"),
                            ("reviewer", "外贸公司复核负责人"),
                        ],
                        max_length=30,
                        verbose_name="备注人角色",
                    ),
                ),
                (
                    "note_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="备注时间"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_notes",
                        to="orders.foreigntradeorder",
                        verbose_name="外贸订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计备注",
                "verbose_name_plural": "审计备注",
                "db_table": "audit_note",
                "ordering": ["-note_time"],
            },
        ),
    ]
