const ROLES = {
  STORE_CLERK: 'store_clerk',
  PHARMACIST: 'pharmacist',
  AREA_MANAGER: 'area_manager'
};

const ROLE_NAMES = {
  [ROLES.STORE_CLERK]: '门店店员',
  [ROLES.PHARMACIST]: '执业药师',
  [ROLES.AREA_MANAGER]: '区域经理'
};

const ORDER_STATUS = {
  PENDING_SIGN: 'pending_sign',
  ABNORMAL_RETURN: 'abnormal_return',
  SIGNED: 'signed',
  MATERIAL_SHORTAGE: 'material_shortage',
  OVERDUE: 'overdue',
  RETURNED_CORRECTION: 'returned_correction'
};

const STATUS_NAMES = {
  [ORDER_STATUS.PENDING_SIGN]: '待签收',
  [ORDER_STATUS.ABNORMAL_RETURN]: '异常回传',
  [ORDER_STATUS.SIGNED]: '签收完成',
  [ORDER_STATUS.MATERIAL_SHORTAGE]: '缺料',
  [ORDER_STATUS.OVERDUE]: '逾期',
  [ORDER_STATUS.RETURNED_CORRECTION]: '退回补正'
};

const STATUS_TRANSITIONS = {
  [ROLES.STORE_CLERK]: {
    initial: [ORDER_STATUS.PENDING_SIGN],
    from: {
      [ORDER_STATUS.RETURNED_CORRECTION]: [ORDER_STATUS.PENDING_SIGN]
    }
  },
  [ROLES.PHARMACIST]: {
    from: {
      [ORDER_STATUS.PENDING_SIGN]: [ORDER_STATUS.SIGNED, ORDER_STATUS.MATERIAL_SHORTAGE, ORDER_STATUS.OVERDUE, ORDER_STATUS.ABNORMAL_RETURN],
      [ORDER_STATUS.ABNORMAL_RETURN]: [ORDER_STATUS.SIGNED, ORDER_STATUS.RETURNED_CORRECTION]
    }
  },
  [ROLES.AREA_MANAGER]: {
    from: {
      [ORDER_STATUS.SIGNED]: [ORDER_STATUS.SIGNED],
      [ORDER_STATUS.MATERIAL_SHORTAGE]: [ORDER_STATUS.PENDING_SIGN, ORDER_STATUS.RETURNED_CORRECTION],
      [ORDER_STATUS.OVERDUE]: [ORDER_STATUS.RETURNED_CORRECTION, ORDER_STATUS.SIGNED],
      [ORDER_STATUS.ABNORMAL_RETURN]: [ORDER_STATUS.RETURNED_CORRECTION, ORDER_STATUS.SIGNED]
    }
  }
};

const ABNORMAL_TYPES = {
  MATERIAL_SHORTAGE: 'material_shortage',
  OVERDUE: 'overdue',
  STATE_CONFLICT: 'state_conflict',
  UNAUTHORIZED: 'unauthorized',
  DUPLICATE_SUBMIT: 'duplicate_submit',
  OLD_VERSION: 'old_version',
  MISSING_EVIDENCE: 'missing_evidence'
};

const ABNORMAL_NAMES = {
  [ABNORMAL_TYPES.MATERIAL_SHORTAGE]: '缺料',
  [ABNORMAL_TYPES.OVERDUE]: '逾期',
  [ABNORMAL_TYPES.STATE_CONFLICT]: '状态冲突',
  [ABNORMAL_TYPES.UNAUTHORIZED]: '越权操作',
  [ABNORMAL_TYPES.DUPLICATE_SUBMIT]: '重复提交',
  [ABNORMAL_TYPES.OLD_VERSION]: '旧版本提交',
  [ABNORMAL_TYPES.MISSING_EVIDENCE]: '缺证据'
};

const WARNING_LEVELS = {
  NORMAL: 'normal',
  APPROACHING: 'approaching',
  OVERDUE: 'overdue'
};

const WARNING_NAMES = {
  [WARNING_LEVELS.NORMAL]: '正常',
  [WARNING_LEVELS.APPROACHING]: '临期',
  [WARNING_LEVELS.OVERDUE]: '逾期'
};

module.exports = {
  ROLES,
  ROLE_NAMES,
  ORDER_STATUS,
  STATUS_NAMES,
  STATUS_TRANSITIONS,
  ABNORMAL_TYPES,
  ABNORMAL_NAMES,
  WARNING_LEVELS,
  WARNING_NAMES
};
