# Generated by Django 5.0.6 on 2026-06-11 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistanceApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_no", models.CharField(max_length=50, unique=True)),
                ("applicant_name", models.CharField(max_length=100)),
                ("applicant_id_card", models.CharField(max_length=18)),
                ("applicant_phone", models.CharField(max_length=20)),
                ("community", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("family_situation", models.TextField()),
                ("difficulty_type", models.CharField(max_length=50)),
                ("application_reason", models.TextField()),
                (
                    "apply_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "current_node",
                    models.CharField(
                        choices=[
                            ("difficulty_support", "困难帮扶"),
                            ("home_verification", "入户核实"),
                            ("rescue_confirmation", "救助确认"),
                        ],
                        default="difficulty_support",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待接单"),
                            ("accepted", "已接单"),
                            ("passed", "验收通过"),
                            ("returned", "退回补正"),
                            ("rejected", "不予通过"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "warning_status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("approaching", "临期"),
                            ("overdue", "逾期"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("node_deadline", models.DateTimeField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handling_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leader_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "street_clerk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clerk_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assistance_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField()),
                ("evidence_type", models.CharField(blank=True, max_length=50)),
                ("is_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="assistance.assistanceapplication",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attachment",
            },
        ),
        migrations.CreateModel(
            name="AuditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node",
                    models.CharField(
                        choices=[
                            ("difficulty_support", "困难帮扶"),
                            ("home_verification", "入户核实"),
                            ("rescue_confirmation", "救助确认"),
                        ],
                        max_length=30,
                    ),
                ),
                ("note_type", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_notes",
                        to="assistance.assistanceapplication",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_note",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExceptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(blank=True, max_length=50)),
                ("exception_type", models.CharField(max_length=100)),
                ("error_code", models.CharField(max_length=50)),
                ("error_message", models.TextField()),
                ("request_data", models.TextField(blank=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exception_logs",
                        to="assistance.assistanceapplication",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exception_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exception_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node",
                    models.CharField(
                        choices=[
                            ("difficulty_support", "困难帮扶"),
                            ("home_verification", "入户核实"),
                            ("rescue_confirmation", "救助确认"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "待接单"),
                            ("accepted", "已接单"),
                            ("passed", "验收通过"),
                            ("returned", "退回补正"),
                            ("rejected", "不予通过"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "待接单"),
                            ("accepted", "已接单"),
                            ("passed", "验收通过"),
                            ("returned", "退回补正"),
                            ("rejected", "不予通过"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("processing_time", models.DateTimeField(auto_now_add=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_records",
                        to="assistance.assistanceapplication",
                    ),
                ),
                (
                    "new_handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "processing_record",
                "ordering": ["-processing_time"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("community_worker", "社区专干"),
                            ("street_clerk", "街道科员"),
                            ("leader", "分管领导"),
                        ],
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
    ]
