# Generated by Django 5.0.6 on 2026-06-11 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CONSULTANT", "车源顾问"),
                            ("EVALUATOR", "评估师"),
                            ("MANAGER", "门店经理"),
                        ],
                        max_length=20,
                    ),
                ),
                ("store_name", models.CharField(default="", max_length=100)),
            ],
            options={
                "verbose_name": "操作人",
                "verbose_name_plural": "操作人",
            },
        ),
        migrations.CreateModel(
            name="VehicleListingApplication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("application_no", models.CharField(max_length=32, unique=True)),
                ("brand", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("vin", models.CharField(max_length=17)),
                ("license_plate", models.CharField(max_length=20)),
                ("mileage", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("PENDING_SUPPLEMENT", "待补正"),
                            ("PENDING_PROCESS", "待处理"),
                            ("PROCESSING", "处理中"),
                            ("UNDER_REVIEW", "复核中"),
                            ("COMPLETED", "办结"),
                            ("RETURNED", "退回补正"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("store_name", models.CharField(max_length=100)),
                ("has_listing_evidence", models.BooleanField(default=False)),
                ("missing_evidence_reason", models.TextField(blank=True, default="")),
                ("supplement_remark", models.TextField(blank=True, default="")),
                ("evaluation_result", models.TextField(blank=True, default="")),
                ("review_result", models.TextField(blank=True, default="")),
                ("reject_reason", models.TextField(blank=True, default="")),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="listings.operator",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluated",
                        to="listings.operator",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed",
                        to="listings.operator",
                    ),
                ),
            ],
            options={
                "verbose_name": "车源上架单",
                "verbose_name_plural": "车源上架单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("operator_role", models.CharField(max_length=20)),
                ("action", models.CharField(max_length=50)),
                ("from_status", models.CharField(max_length=30)),
                ("to_status", models.CharField(max_length=30)),
                ("remark", models.TextField(blank=True, default="")),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="listings.operator",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_records",
                        to="listings.vehiclelistingapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "处理记录",
                "verbose_name_plural": "处理记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditNote",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("operator_role", models.CharField(max_length=20)),
                ("note", models.TextField()),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="listings.operator",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_notes",
                        to="listings.vehiclelistingapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计备注",
                "verbose_name_plural": "审计备注",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="listings.operator",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="listings.vehiclelistingapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "附件",
                "verbose_name_plural": "附件",
            },
        ),
    ]
