export const ROLE_KEYS = {
  PROJECT_ASSISTANT: 'PROJECT_ASSISTANT',
  DELIVERY_REGISTRAR: 'DELIVERY_REGISTRAR',
  DEV_LEAD: 'DEV_LEAD',
  AUDIT_SUPERVISOR: 'AUDIT_SUPERVISOR',
  DELIVERY_MANAGER: 'DELIVERY_MANAGER',
  REVIEW_LEADER: 'REVIEW_LEADER'
}

export const ROLE_LABELS = {
  [ROLE_KEYS.PROJECT_ASSISTANT]: '项目助理',
  [ROLE_KEYS.DELIVERY_REGISTRAR]: '需求交付登记员',
  [ROLE_KEYS.DEV_LEAD]: '开发负责人',
  [ROLE_KEYS.AUDIT_SUPERVISOR]: '需求交付审核主管',
  [ROLE_KEYS.DELIVERY_MANAGER]: '交付经理',
  [ROLE_KEYS.REVIEW_LEADER]: '软件外包项目组复核负责人'
}

export const ROLE_COLORS = {
  [ROLE_KEYS.PROJECT_ASSISTANT]: 'blue',
  [ROLE_KEYS.DELIVERY_REGISTRAR]: 'cyan',
  [ROLE_KEYS.DEV_LEAD]: 'green',
  [ROLE_KEYS.AUDIT_SUPERVISOR]: 'purple',
  [ROLE_KEYS.DELIVERY_MANAGER]: 'geekblue',
  [ROLE_KEYS.REVIEW_LEADER]: 'orange'
}

export const DEMO_ACCOUNTS = [
  { username: 'project_assistant', role: ROLE_KEYS.PROJECT_ASSISTANT, label: ROLE_LABELS[ROLE_KEYS.PROJECT_ASSISTANT] },
  { username: 'delivery_registrar', role: ROLE_KEYS.DELIVERY_REGISTRAR, label: ROLE_LABELS[ROLE_KEYS.DELIVERY_REGISTRAR] },
  { username: 'dev_lead', role: ROLE_KEYS.DEV_LEAD, label: ROLE_LABELS[ROLE_KEYS.DEV_LEAD] },
  { username: 'audit_supervisor', role: ROLE_KEYS.AUDIT_SUPERVISOR, label: ROLE_LABELS[ROLE_KEYS.AUDIT_SUPERVISOR] },
  { username: 'delivery_manager', role: ROLE_KEYS.DELIVERY_MANAGER, label: ROLE_LABELS[ROLE_KEYS.DELIVERY_MANAGER] },
  { username: 'review_leader', role: ROLE_KEYS.REVIEW_LEADER, label: ROLE_LABELS[ROLE_KEYS.REVIEW_LEADER] },
  { username: 'audit_supervisor_2', role: ROLE_KEYS.AUDIT_SUPERVISOR, label: '需求交付审核主管(二)' },
  { username: 'delivery_manager_2', role: ROLE_KEYS.DELIVERY_MANAGER, label: '交付经理(二)' },
]

export const ORDER_STATUS_KEYS = {
  PENDING_VERIFY: 'PENDING_VERIFY',
  VERIFY_FAILED: 'VERIFY_FAILED',
  VERIFY_COMPLETED: 'VERIFY_COMPLETED',
  REQUIREMENT_SUBMITTED: 'REQUIREMENT_SUBMITTED',
  REQUIREMENT_AUDITED: 'REQUIREMENT_AUDITED',
  SCHEDULE_SUBMITTED: 'SCHEDULE_SUBMITTED',
  SCHEDULE_AUDITED: 'SCHEDULE_AUDITED',
  DELIVERY_SUBMITTED: 'DELIVERY_SUBMITTED',
  DELIVERY_AUDITED: 'DELIVERY_AUDITED',
  REVIEW_PENDING: 'REVIEW_PENDING',
  REVIEW_COMPLETED: 'REVIEW_COMPLETED',
  ARCHIVED: 'ARCHIVED'
}

export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS_KEYS.PENDING_VERIFY]: '待核验',
  [ORDER_STATUS_KEYS.VERIFY_FAILED]: '核验失败',
  [ORDER_STATUS_KEYS.VERIFY_COMPLETED]: '核验完成',
  [ORDER_STATUS_KEYS.REQUIREMENT_SUBMITTED]: '需求确认待审核',
  [ORDER_STATUS_KEYS.REQUIREMENT_AUDITED]: '需求确认已审核',
  [ORDER_STATUS_KEYS.SCHEDULE_SUBMITTED]: '排期评估待审核',
  [ORDER_STATUS_KEYS.SCHEDULE_AUDITED]: '排期评估已审核',
  [ORDER_STATUS_KEYS.DELIVERY_SUBMITTED]: '交付验收待审核',
  [ORDER_STATUS_KEYS.DELIVERY_AUDITED]: '交付验收已审核',
  [ORDER_STATUS_KEYS.REVIEW_PENDING]: '待复核',
  [ORDER_STATUS_KEYS.REVIEW_COMPLETED]: '复核完成',
  [ORDER_STATUS_KEYS.ARCHIVED]: '已归档'
}

export const ORDER_STATUS_COLORS = {
  [ORDER_STATUS_KEYS.PENDING_VERIFY]: 'gold',
  [ORDER_STATUS_KEYS.VERIFY_FAILED]: 'red',
  [ORDER_STATUS_KEYS.VERIFY_COMPLETED]: 'blue',
  [ORDER_STATUS_KEYS.REQUIREMENT_SUBMITTED]: 'cyan',
  [ORDER_STATUS_KEYS.REQUIREMENT_AUDITED]: 'blue',
  [ORDER_STATUS_KEYS.SCHEDULE_SUBMITTED]: 'cyan',
  [ORDER_STATUS_KEYS.SCHEDULE_AUDITED]: 'blue',
  [ORDER_STATUS_KEYS.DELIVERY_SUBMITTED]: 'cyan',
  [ORDER_STATUS_KEYS.DELIVERY_AUDITED]: 'blue',
  [ORDER_STATUS_KEYS.REVIEW_PENDING]: 'purple',
  [ORDER_STATUS_KEYS.REVIEW_COMPLETED]: 'green',
  [ORDER_STATUS_KEYS.ARCHIVED]: 'default'
}

export const MODULE_STATUS_KEYS = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  EXCEPTION: 'EXCEPTION'
}

export const MODULE_STATUS_LABELS = {
  [MODULE_STATUS_KEYS.NOT_STARTED]: '未开始',
  [MODULE_STATUS_KEYS.IN_PROGRESS]: '进行中',
  [MODULE_STATUS_KEYS.COMPLETED]: '已完成',
  [MODULE_STATUS_KEYS.EXCEPTION]: '异常'
}

export const MODULE_STATUS_COLORS = {
  [MODULE_STATUS_KEYS.NOT_STARTED]: 'default',
  [MODULE_STATUS_KEYS.IN_PROGRESS]: 'blue',
  [MODULE_STATUS_KEYS.COMPLETED]: 'green',
  [MODULE_STATUS_KEYS.EXCEPTION]: 'red'
}

export const MODULE_TYPE_KEYS = {
  REQUIREMENT: 'REQUIREMENT',
  SCHEDULE: 'SCHEDULE',
  DELIVERY: 'DELIVERY'
}

export const MODULE_TYPE_LABELS = {
  [MODULE_TYPE_KEYS.REQUIREMENT]: '需求确认',
  [MODULE_TYPE_KEYS.SCHEDULE]: '排期评估',
  [MODULE_TYPE_KEYS.DELIVERY]: '交付验收'
}

export const ACTION_KEYS = {
  SUBMIT: 'SUBMIT',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  CORRECT: 'CORRECT',
  ADVANCE: 'ADVANCE',
  REVIEW: 'REVIEW',
  ARCHIVE: 'ARCHIVE'
}

export const ACTION_LABELS = {
  [ACTION_KEYS.SUBMIT]: '提交',
  [ACTION_KEYS.APPROVE]: '审核通过',
  [ACTION_KEYS.REJECT]: '审核驳回',
  [ACTION_KEYS.CORRECT]: '补正',
  [ACTION_KEYS.ADVANCE]: '推进',
  [ACTION_KEYS.REVIEW]: '复核',
  [ACTION_KEYS.ARCHIVE]: '归档'
}

export const WARNING_LEVELS = {
  NORMAL: 'normal',
  WARNING: 'warning',
  OVERDUE: 'overdue'
}

export const WARNING_LABELS = {
  [WARNING_LEVELS.NORMAL]: '正常',
  [WARNING_LEVELS.WARNING]: '临期',
  [WARNING_LEVELS.OVERDUE]: '逾期'
}

export const WARNING_COLORS = {
  [WARNING_LEVELS.NORMAL]: 'green',
  [WARNING_LEVELS.WARNING]: 'gold',
  [WARNING_LEVELS.OVERDUE]: 'red'
}

export const BATCH_ACTIONS = [
  { value: 'advance', label: '推进' },
  { value: 'verify', label: '核验' }
]

export const LIST_STATUS_OPTIONS = [
  { value: ORDER_STATUS_KEYS.PENDING_VERIFY, label: ORDER_STATUS_LABELS[ORDER_STATUS_KEYS.PENDING_VERIFY] },
  { value: ORDER_STATUS_KEYS.VERIFY_FAILED, label: ORDER_STATUS_LABELS[ORDER_STATUS_KEYS.VERIFY_FAILED] },
  { value: ORDER_STATUS_KEYS.VERIFY_COMPLETED, label: ORDER_STATUS_LABELS[ORDER_STATUS_KEYS.VERIFY_COMPLETED] }
]
